### ISSUE TITLE
Closed Dispute Blank at First

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1015]
> I closed my first dispute today and my discovered a tiny bug. Everytime I open the "closed" dispute the summary page is empty / blank / white. I need to click on Summary to display the content of the dispute.

The user "anyone" on Slack reported the issue above. It needs to be reproduced.

**Comment by rmisio** [comment]
It would be useful if he could provide the case api payload and also if he could see if there are any errors in the console.

**Comment by rmisio** [comment]
Here's the exception that's thrown (still waiting on "anyone" to provide the case payload):

```
VM631:10 Uncaught TypeError: Cannot read property 'amount' of undefined
    at _.forEach.type (eval at _.template (/usr/lib/openbazaar2/resources/app/node_modules/underscore/underscore.js:1454:20), <anonymous>:10:78)
    at Array.forEach (native)
    at eval (eval at _.template (/usr/lib/openbazaar2/resources/app/node_modules/underscore/underscore.js:1454:20), <anonymous>:9:36)
    at template (/usr/lib/openbazaar2/resources/app/node_modules/underscore/underscore.js:1461:21)
    at wrappedTmpl (/usr/lib/openbazaar2/resources/app/prod/utils/loadTemplate.js:52:14)
    at /usr/lib/openbazaar2/resources/app/prod/views/modals/orderDetail/summaryTab/DisputePayout.js:174:25
    at sendBackTmpl (/usr/lib/openbazaar2/resources/app/prod/utils/loadTemplate.js:54:5)
    at loadTemplate (/usr/lib/openbazaar2/resources/app/prod/utils/loadTemplate.js:73:5)
    at _class.render (/usr/lib/openbazaar2/resources/app/prod/views/modals/orderDetail/summaryTab/DisputePayout.js:173:34)
    at _class.setState (/usr/lib/openbazaar2/resources/app/prod/views/modals/orderDetail/summaryTab/DisputePayout.js:157:14)
```

**Comment by rmisio** [comment]
```
{
timestamp: "2017-10-10T17:06:13.000Z",
buyerContract: {},
state: "RESOLVED",
read: true,
buyerOpened: true,
claim: "Magic Coin stated 3 days ago that this order was not yet funded. I explained to him to go to Settings --&gt; Advanced, click Reload Transactions. No response since that time.",
unreadChatMessages: 0,
resolution: {}
}
```

**Comment by rmisio** [comment]
This is happening because the server is returning an empty `resolution` object. The expectation is that when a case is in a state of `RESOLVED` a `resolution` object is provided with details about the final payout.

A [server](https://github.com/OpenBazaar/openbazaar-go/issues/740) bug has been logged.
