### ISSUE TITLE
Can't run OpenBazaar after new install

### ISSUE THREAD

**Issue by CarbonMan** [OpenBazaar/openbazaar-desktop#1114]
Windows 8.1
node version 6.9.1

It's a fresh install of OpenBazaar. I am following the instructions from [](https://github.com/OpenBazaar/openbazaar-desktop)
Installed without errors.
When I get to "npm start" it runs electron but the page is blank.
Looking at the devtools it has the message

Uncaught Error: Cannot find module 'sifter'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (D:\learning\Open bazaar\openbazaar-desktop\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at regex (D:/learning/Open bazaar/openbazaar-desktop/js/lib/selectize.js:34:49)
    at Object.<anonymous> (D:/learning/Open bazaar/openbazaar-desktop/js/lib/selectize.js:30:2)
    at Object.<anonymous> (D:\learning\Open bazaar\openbazaar-desktop\js\lib\selectize.js:3229:3)
    at Module._compile (module.js:571:32)
    at loader (D:\learning\Open bazaar\openbazaar-desktop\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\learning\Open bazaar\openbazaar-desktop\node_modules\babel-register\lib\node.js:154:7)

Any suggestions?

**Comment by jjeffryes** [comment]
Did you run `npm install` before `npm start`?

**Comment by CarbonMan** [comment]
I ran "npm install" again and still got the error

So then I ran
`npm install sifter --save`
errors...
`npm install microplugin --save`

and then I got OpenBazaar started with no errors.

**Comment by CarbonMan** [comment]
Should sifter and microplugin be added to package.json? Happy to do it, as I need to learn how to contribute.

**Comment by rmisio** [comment]
> Should sifter and microplugin be added to package.json?

I don't think so. Those are dependencies required by the selectize lib and the lib declares them as dependencies, so I'm not sure why you would get the error you were getting. We'll have to keep an eye out if others are running into this issue.
