### ISSUE TITLE
Update process needs some work

### ISSUE THREAD

**Issue by EchterAgo** [OpenBazaar/openbazaar-desktop#1364]
Brief Description: There are problems with the in-app updater, at least on Windows. My first update was from v2.1.0 to v2.1.1 and it resulted in an OpenBazaar installation that started, but always resulted in a "failed to connect to server" message. I managed to fix this by uninstalling and reinstalling using the v2.1.1 installer. My second update was from v2.1.1 to v2.2.0 and it resulted in nothing happening when I start the OpenBazaar shortcut in the start menu. I had a look in the directory where the shortcut is pointed and there is a OpenBazaar2.exe with a modification date of 2018-04-15 and an OpenBazaar2Client.exe with a modification date of 2018-05-17. Starting the OpenBazaar2Client.exe actually starts the client, but again, it just goes to the "failed to connect to server" screen.

Operating System (OS and version): Windows 10 Pro x64
OpenBazaar version (shown on `About OpenBazaar` page in menu): I can not access that menu from the "failed to connect" screen, but it should be v2.2.0
Hardware: Core i7 4770, ASUS Z87-PRO, 16GB RAM, Radeon R9 280X, Samsung 850 PRO SSD

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): It happened on 2 updates now.

Steps to reproduce:
1. Update OpenBazaar on Windows 10 using the in-app update mechanism

Observed Behavior:
OpenBazaar does not start its server and ends up on the "failed to connect to server" screen.

Expected Behavior:
OpenBazaar works.

Additional info (links, images, etc go here): I'm going to leave my installation in this state for now, in case someone wants additional info to figure out what has gone wrong. BTW, why does the OpenBazaar2.exe have a "Copyright (C) 2015 GitHub, Inc"?

**Comment by EchterAgo** [comment]
Just found the updater log file, maybe this is of some use to diagnose the issue.

[SquirrelSetup.log](https://github.com/OpenBazaar/openbazaar-desktop/files/2019250/SquirrelSetup.log)

**Comment by jjeffryes** [comment]
The failed to connect to server screen should have a link to show the contents of your ob.log file. Can you copy and paste those here? It sounds like the server won't start after the update, the ob.log file should show an error explaining why.

**Comment by jjeffryes** [comment]
@hoffmabc the squirrel log shows an error, but I'm not sure why that would break the server install.

```
2018-05-19 00:05:09> Program: Starting Squirrel Updater: --processStartAndWait OpenBazaar2.exe
2018-05-19 00:05:09> Program: Want to launch 'C:\Users\axel\AppData\Local\OpenBazaar2\app-2.2.0\OpenBazaar2.exe'
2018-05-19 00:05:09> Program: File C:\Users\axel\AppData\Local\OpenBazaar2\app-2.2.0\OpenBazaar2.exe doesn't exist in current release
2018-05-19 00:05:09> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

Any idea why the above is happening?

**Comment by EchterAgo** [comment]
I don't see a link to show the ob.log, but I found it in C:\Users\axel\OpenBazaar2.0-bitcoincash\logs

[ob.log](https://github.com/OpenBazaar/openbazaar-desktop/files/2019628/ob.log)

**Comment by EchterAgo** [comment]
It seems the file does not have any date stamps, only time. From glancing over it I don't see anything obviously helpful.

**Comment by jjeffryes** [comment]
It looks like the server is running, which makes it very strange the client can't connect to it. 

Any thoughts here, @cpacia or @tyler-smith ?

**Comment by EchterAgo** [comment]
Ah, right, I remember what I saw last time. OpenBazaar seems to be installed to C:\Users\axel\AppData\Local\OpenBazaar2 now. There I am seeing 2 exe files, with the wrong one being started from the start menu after update.

I have 2 subfolders for the current and the previous OpenBazaar versions, app-2.1.1 and app-2.2.0. The thing is, in the app-2.2.0 folder, the server is not included under resources\openbazaar-go.

So yea, after using the updater there is no 2.2.0 openbazaard.exe

**Comment by hoffmabc** [comment]
If the server is not included in the resources folder then either you accidentally got the client only binary somehow or there was an error in the build.

**Comment by EchterAgo** [comment]
Can confirm that the issue has been resolved. Just used the built in updater to go from 2.2.0 to 2.2.1.
