### ISSUE TITLE
2.2.2 RC1 Listing Retrieval Errors

### ISSUE THREAD

**Issue by christroutner** [OpenBazaar/openbazaar-desktop#1456]
Brief Description: 
Saw this happened twice. Managed to catch it 'red handed' the second time it occurred. This is using the 2.2.2 RC1 desktop client to access a remote server running 0.12.1-RC2 as buyer. Trying to make a purchase from another remote server running 0.12.1-RC2 as seller. Both servers are on Digital Ocean, so no firewalls.

Operating System (OS and version): Windows 10 home
OpenBazaar version (shown on `About OpenBazaar` page in menu): 
Hardware: 2.2.2

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Sometimes

I'll attach a screenshot too, but here is the output from the OB client console:
```
Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---


C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600 GET http://165.227.63.21:4002/ob/listings/QmZzUhbfGMeQ8a9nJQFAxE96cUaWKjx27zMXzRz3F6zPMi 404 (Not Found)
send @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600
ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9206
Backbone.ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1460
Backbone.sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1443
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:798
fetch @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1055
createStoreTabView @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\userPage\UserPage.…:304
selectTab @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\userPage\UserPage.…:361
setState @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\userPage\UserPage.…:319
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\userPage\UserPage.…:423
sendBackTmpl @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\utils\loadTemplate.js:54
loadTemplate @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\utils\loadTemplate.js:73
render @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\userPage\UserPage.…:386
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\router.js:568
fire @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:3268
fireWith @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:3398
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\lib\whenAll.jquery.js:28
fire @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:3268
fireWith @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:3398
done @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9305
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9548
C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600 GET http://165.227.63.21:4002/ob/listing/QmSfEmLsYTC35xuU2bpZ7e8m2j7wEunuGGVLkJ3TEvvAyH/test-ob2 500 (Internal Server Error)
send @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600
ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9206
Backbone.ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1460
Backbone.sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1443
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:437
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\models\BaseModel.js:316
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\models\listing\Listing.js:346
fetch @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:599
fetchFullListing @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\ListingCard.js:428
onClick @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\ListingCard.js:328
executeBound @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:762
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:775
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:122
dispatch @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:5183
elemData.handle @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:4991
```

**Comment by christroutner** [comment]
![image](https://user-images.githubusercontent.com/9870991/43038374-bff131e8-8ccc-11e8-85fb-4aa0c1f2b46f.png)

**Comment by christroutner** [comment]
![image](https://user-images.githubusercontent.com/9870991/43038389-e88bb290-8ccc-11e8-9170-80ca71737a9a.png)

**Comment by christroutner** [comment]
This error is happening very consistently. To repeat:

This is using the 2.2.2 RC1 desktop client to access a remote server running 0.12.1-RC2 as buyer. Trying to make a purchase from another remote server running 0.12.1-RC2 as seller. Both servers are on Digital Ocean, so no firewalls.

So I am unable to purchase listings from one remote server as buyer to another remote server as seller.

**Comment by christroutner** [comment]
I investigated this a little further, with the developer tools open.

Here is the error that pops up in the dev tools console, along with the call stack:
```
C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600 GET http://165.227.63.21:4002/ob/listing/QmSfEmLsYTC35xuU2bpZ7e8m2j7wEunuGGVLkJ3TEvvAyH/test-ob2 500 (Internal Server Error)

GET http://165.227.63.21:4002/ob/listing/QmSfEmLsYTC35xuU2bpZ7e8m2j7wEunuGGVLkJ3TEvvAyH/test-ob2 500 (Internal Server Error)
send @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9600
ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:9206
Backbone.ajax @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1460
Backbone.sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:1443
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:437
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\models\BaseModel.js:316
sync @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\models\listing\Listing.js:346
fetch @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\backbone\backbon…:599
fetchFullListing @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\ListingCard.js:428
onClick @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\prod\views\ListingCard.js:328
executeBound @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:762
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:775
(anonymous) @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\underscore\under…:122
dispatch @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:5183
elemData.handle @ C:\Users\Chris\AppData\Local\OpenBazaar2\app-2.2.2\resources\app.asar\node_modules\jquery\dist\jque…:4991
```

**Comment by jjeffryes** [comment]
Is QmSfEmLsYTC35xuU2bpZ7e8m2j7wEunuGGVLkJ3TEvvAyH still on the network? I'm unable to find that node at all.

**Comment by christroutner** [comment]
@jjeffryes Yes, it's been up the whole time. It's a remote server on a DO droplet.
ob://QmSfEmLsYTC35xuU2bpZ7e8m2j7wEunuGGVLkJ3TEvvAyH/store

**Comment by jjeffryes** [comment]
I wasn't able to reach the node last night, but today I can. Local versions of the app are able to retrieve that listing normally. I haven't tried with a remote server yet.
