### ISSUE TITLE
Undefined in ListingCard

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#1471]
Countly is reporting an error in the listing card view. 

Mac has reported the error for 100 users 176 times on 2.2.1.
Mac has reported the error for 80 users 159 times on 2.2.0.
Linux has reported the error for 91 users 220 times on 2.2.1.

I haven't found a report of this error on Windows.

This looks like it's happening in the fetchFullListing method when the listing card is in the search results.

I have not yet reproduced the error.

```
TypeError: Cannot read property 'reason' of undefined
    at Object.<anonymous> (/Applications/OpenBazaar2.app/Contents/Resources/app/prod/views/ListingCard.js:355:39)
    at fire (/Applications/OpenBazaar2.app/Contents/Resources/app
ode_modules/jquery/dist/jquery.js:3268:31)
    at Object.fireWith [as rejectWith] (/Applications/OpenBazaar2.app/Contents/Resources/app
ode_modules/jquery/dist/jquery.js:3398:7)
    at done (/Applications/OpenBazaar2.app/Contents/Resources/app
ode_modules/jquery/dist/jquery.js:9307:14)
    at Object.abort (/Applications/OpenBazaar2.app/Contents/Resources/app
ode_modules/jquery/dist/jquery.js:9028:6)
    at _class.remove (/Applications/OpenBazaar2.app/Contents/Resources/app/prod/views/ListingCard.js:464:56)
    at /Applications/OpenBazaar2.app/Contents/Resources/app/prod/views/search/Results.js:216:19
    at Array.forEach (<anonymous>)
    at _class.removeCardViews (/Applications/OpenBazaar2.app/Contents/Resources/app/prod/views/search/Results.js:215:22)
    at _class.remove (/Applications/OpenBazaar2.app/Contents/Resources/app/prod/views/search/Results.js:223:12)
```

**Comment by jjeffryes** [comment]
On further research, this happens when a listing is taking a very long time to load and the back button is pressed.
