### ISSUE TITLE
Currency tests fail due to undefined ajax in test

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#341]
When the automated tests are run, the following errors are  thrown:

```
  2) the currency utility module has functions that involve converting between currencies "before all" hook:
     TypeError: Attempted to wrap undefined property ajax as function
      at Object.wrapMethod (C:\Users\J\ob\openbazaar-desktop\node_modules\sinon\lib\sinon\util\core.js:113:29)
      at Object.stub (C:\Users\J\ob\openbazaar-desktop\node_modules\sinon\lib\sinon\stub.js:67:26)
      at Context.<anonymous> (currency.js:158:20)
      at callFn (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runnable.js:326:21)
      at Hook.Runnable.run (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runnable.js:319:7)
      at next (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runner.js:320:5)

  3) the currency utility module has functions that involve converting between currencies "after all" hook:
     TypeError: Cannot read property 'restore' of undefined
      at Context.<anonymous> (currency.js:235:7)
      at callFn (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runnable.js:326:21)
      at Hook.Runnable.run (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runnable.js:319:7)
      at next (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (C:\Users\J\ob\openbazaar-desktop\node_modules\mocha\lib\runner.js:320:5)
```

It doesn't look like these errors happen in Travis, they may be a Windows problem, similar to the issue where jsDoc fails in Windows.

**Comment by hoffmabc** [comment]
I'm not sure what the action is here.

**Comment by jjeffryes** [comment]
This is the bug for those tests that are broken (at least for me) in Windows. See the comment on #342

**Comment by rmisio** [comment]
There's a worrisome inconsistency between the tests on Windows vs. other OSs. It's on my to-do list to set up a Win VM and get to the bottom of the mis-behavior on Windows.

**Comment by jjeffryes** [comment]
This hasn't been an issue for a while.
