### ISSUE TITLE
Contract is Not Shown In Order Details

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#613]
When the contract link in the order details modal is clicked, the contract is loaded from the API, but is not appended to the DOM. 

![image](https://user-images.githubusercontent.com/1584275/28997005-fe0068da-79d8-11e7-83cd-890fc50d8f11.png)

![image](https://user-images.githubusercontent.com/1584275/28997007-0d3fc250-79d9-11e7-974e-8ebbe4980bd7.png)

**Comment by rmisio** [comment]
Are there any errors in the JS console?

**Comment by jjeffryes** [comment]
file:///C:/Users/J/ob/openbazaar-desktop/js/views/modals/orderDetail/Contract.js

Uncaught TypeError: Cannot read property 'set_show_to_level' of undefined
    at C:/Users/J/ob/openbazaar-desktop/js/views/modals/orderDetail/Contract.js:78:19
    at sendBackTmpl (C:/Users/J/ob/openbazaar-desktop/js/utils/loadTemplate.js:25:5)
    at loadTemplate (C:/Users/J/ob/openbazaar-desktop/js/utils/loadTemplate.js:44:5)
    at _class.render (C:/Users/J/ob/openbazaar-desktop/js/views/modals/orderDetail/Contract.js:73:5)
    at _class.selectTab (C:/Users/J/ob/openbazaar-desktop/js/views/modals/orderDetail/OrderDetail.js:290:17)
    at _class.onTabClick (C:/Users/J/ob/openbazaar-desktop/js/views/modals/orderDetail/OrderDetail.js:160:10)
    at HTMLDivElement.dispatch (C:\Users\J\ob\openbazaar-desktop\node_modules\jquery\dist\jquery.js:5201:27)
    at HTMLDivElement.elemData.handle (C:\Users\J\ob\openbazaar-desktop\node_modules\jquery\dist\jquery.js:5009:28)

**Comment by rmisio** [comment]
This is because the reporter of this bug blew away this line `<script src="../js/lib/renderjson.js"></script>` 24 days ago... lol:

https://github.com/OpenBazaar/openbazaar-desktop/commit/f527597842b38bbe25c36cb42d204f16747e7e72

**Comment by jjeffryes** [comment]
Where's that shame emoji?
