### ISSUE TITLE
"A JavaScript error occured in the main process"

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/openbazaar-desktop#949]
Brief Description: 

```
Uncaught Exception:
RangeError: Invalid string length
    at log (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/mainBuilt.js:598:9)
    at LocalServer.<anonymous> (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/mainBuilt.js:606:10)
    at triggerEvents (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/node_modules/backbone/backbone.js:370:57)
    at triggerApi (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/node_modules/backbone/backbone.js:356:19)
    at eventsApi (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/node_modules/backbone/backbone.js:155:16)
    at LocalServer.Events.trigger (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/node_modules/backbone/backbone.js:346:5)
    at LocalServer._log (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/js/utils/localServer.js:288:12)
    at /Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/js/utils/localServer.js:317:23
    at Array.forEach (native)
    at LocalServer.obServerLog (/Volumes/OMEGA/Applications/OpenBazaar2.app/Contents/Resources/app/js/utils/localServer.js:316:26)
```

Operating System (OS and version): OSX 10.12.6
OpenBazaar version (shown on `About OpenBazaar` page in menu): client 2.0.11, server 0.9.1
Hardware: Mid 2011 Mac Mini

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): 
First time this has appeared. Hit OK and it went through a few different permutations, then seemingly repeated one no matter how many times I hit OK, so I force quit.

Steps to reproduce:
1. Launch OB 2.0
2. Use other apps
3. OB 2.0 throws this error in background

**Comment by TheButterZone** [comment]
Just happened again exactly the same.
